services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION:
      LDAP_DOMAIN: "rsup.com"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_BASE_DN: "dc=rsup,dc=com"
      LDAP_BACKEND: "mdb"
      LDAP_READONLY_USER: "true"
      LDAP_TLS: "false"
      LDAP_TLS_VERIFY_CLIENT: "try"
      LDAP_READONLY_USER_USERNAME: "manager"
      LDAP_READONLY_USER_PASSWORD: "manager"
    networks:
      - stf

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "81:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
    networks:
      - stf

  ldap_password:
    image: npenkov/docker-ldap-passwd-webui:latest
    container_name: ldap_password
    ports:
      - "8080:8080"
    environment:
      LPW_TITLE: "Change your password on STF LDAP server"
      LPW_HOST: "openldap"
      LPW_PORT: "389"
      LPW_TYPE: "LDAP"
      LPW_ENCRYPTED: "false"
      LPW_START_TLS: "false"
      LPW_SSL_SKIP_VERIFY: "true"
      LPW_PATTERN: '.{6,}'
      LPW_USER_DN: "cn=%s,ou=stf,dc=rsup,dc=com"
      LPW_USER_BASE: "ou=stf,dc=rsup,dc=com"
      LPW_BIND_DN: "cn=admin,dc=rsup,dc=com"
      LPW_BIND_DN_PASS: "admin"
    depends_on:
      - openldap
    networks:
      - stf

networks:
  stf:
    external: true
